from contextlib import AbstractAsyncContextManager
from typing import Protocol

from app.domain.session.models import (
    Session,
    SessionMessageEntry,
    SessionOperation,
    SessionRun,
    SteeringInput,
)


class SessionRepository(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[None]: ...

    async def defer_foreign_keys(self) -> None: ...

    async def insert_session(self, session: Session) -> None: ...

    async def update_session(self, session: Session) -> None: ...

    async def get_session(self, session_id: str) -> Session | None: ...

    async def list_sessions(self) -> list[Session]: ...

    async def insert_entry(self, entry: SessionMessageEntry) -> None: ...

    async def delete_entries(self, session_id: str, entry_ids: list[str]) -> None: ...

    async def get_entry(
        self, session_id: str, entry_id: str
    ) -> SessionMessageEntry | None: ...

    async def list_entries(self, session_id: str) -> list[SessionMessageEntry]: ...

    async def insert_run(self, run: SessionRun) -> None: ...

    async def delete_runs(self, session_id: str, run_ids: list[str]) -> None: ...

    async def update_run(self, run: SessionRun) -> None: ...

    async def get_run(self, session_id: str, run_id: str) -> SessionRun | None: ...

    async def list_runs(self, session_id: str) -> list[SessionRun]: ...

    async def find_running_run(self) -> SessionRun | None: ...

    async def list_running_runs(self) -> list[SessionRun]: ...

    async def insert_steering(self, steering: SteeringInput) -> None: ...

    async def delete_steering(self, session_id: str, steering_ids: list[str]) -> None: ...

    async def update_steering(self, steering: SteeringInput) -> None: ...

    async def get_steering(
        self, session_id: str, steering_id: str
    ) -> SteeringInput | None: ...

    async def list_steering(
        self, session_id: str, run_id: str
    ) -> list[SteeringInput]: ...

    async def list_pending_steering(
        self, session_id: str, run_id: str
    ) -> list[SteeringInput]: ...

    async def insert_operation(self, operation: SessionOperation) -> None: ...

    async def delete_operations(self, operation_ids: list[str]) -> None: ...

    async def list_operations(self, session_id: str) -> list[SessionOperation]: ...

    async def get_operation(self, operation_id: str) -> SessionOperation | None: ...

    async def insert_operation_invalidation(
        self, operation_id: str, session_id: str
    ) -> None: ...

    async def get_operation_invalidation(self, operation_id: str) -> str | None: ...
