from collections.abc import Callable
from contextlib import AbstractAsyncContextManager
from typing import Protocol

from app.domain.business.models import (
    CatalogExercise,
    ProfileContent,
    ProfileProposalStatus,
    ProfileRecord,
    ProfileSaveRecord,
    ProfileSnapshot,
    WorkoutContent,
    WorkoutListArguments,
    WorkoutListResult,
    WorkoutProposalStatus,
    WorkoutRecord,
    WorkoutSaveRecord,
    WorkoutSnapshot,
)


class BusinessRepository(Protocol):
    def transaction(
        self, veto: Callable[[], bool] | None = None
    ) -> AbstractAsyncContextManager[None]: ...

    async def get_profile(self) -> ProfileRecord | None: ...

    async def save_profile(
        self, content: ProfileContent, version: int, updated_at: int
    ) -> None: ...

    # 画像待确认快照与保存幂等记录。

    async def insert_snapshot(self, snapshot: ProfileSnapshot) -> None: ...

    async def get_snapshot(self, proposal_id: str) -> ProfileSnapshot | None: ...

    async def list_snapshots(self, session_id: str) -> list[ProfileSnapshot]: ...

    async def find_snapshot_by_confirmation(
        self, session_id: str, confirmation_entry_id: str
    ) -> ProfileSnapshot | None: ...

    async def bind_display_entry(
        self, proposal_id: str, display_entry_id: str
    ) -> None: ...

    async def begin_save(self, proposal_id: str, confirmation_entry_id: str) -> None: ...

    async def set_snapshot_status(
        self, proposal_id: str, status: ProfileProposalStatus
    ) -> None: ...

    async def complete_save(self, record: ProfileSaveRecord) -> None: ...

    async def get_save_record(self, proposal_id: str) -> ProfileSaveRecord | None: ...

    async def list_save_records(self, session_id: str) -> list[ProfileSaveRecord]: ...

    async def find_save_record_by_confirmation(
        self, session_id: str, confirmation_entry_id: str
    ) -> ProfileSaveRecord | None: ...

    async def invalidate_pending(
        self, session_id: str, profile_id: int, keep_proposal_id: str
    ) -> None: ...

    async def delete_snapshots_for_entries(
        self, session_id: str, entry_ids: set[str]
    ) -> None: ...

    async def delete_snapshots_for_session(self, session_id: str) -> None: ...

    async def recover_interrupted_saves(self) -> int: ...

    async def get_workout(self, workout_id: str) -> WorkoutRecord | None: ...

    async def get_workout_by_date(self, performed_on: str) -> WorkoutRecord | None: ...

    async def list_workouts(self, arguments: WorkoutListArguments) -> WorkoutListResult: ...

    async def insert_workout(self, record: WorkoutRecord) -> None: ...

    async def update_workout(
        self, workout_id: str, base_version: int, content: WorkoutContent, updated_at: int
    ) -> bool: ...

    async def insert_workout_snapshot(self, snapshot: WorkoutSnapshot) -> None: ...

    async def get_workout_snapshot(self, proposal_id: str) -> WorkoutSnapshot | None: ...

    async def list_workout_snapshots(self, session_id: str) -> list[WorkoutSnapshot]: ...

    async def find_workout_snapshot_by_confirmation(
        self, session_id: str, confirmation_entry_id: str
    ) -> WorkoutSnapshot | None: ...

    async def bind_workout_display_entry(self, proposal_id: str, display_entry_id: str) -> None: ...

    async def begin_workout_save(self, proposal_id: str, confirmation_entry_id: str) -> None: ...

    async def set_workout_snapshot_status(self, proposal_id: str, status: WorkoutProposalStatus) -> None: ...

    async def invalidate_pending_workouts(
        self, session_id: str, performed_on: str, keep_proposal_id: str
    ) -> None: ...

    async def complete_workout_save(self, record: WorkoutSaveRecord) -> None: ...

    async def get_workout_save_record(self, proposal_id: str) -> WorkoutSaveRecord | None: ...

    async def list_workout_save_records(self, session_id: str) -> list[WorkoutSaveRecord]: ...

    async def find_workout_save_record_by_confirmation(
        self, session_id: str, confirmation_entry_id: str
    ) -> WorkoutSaveRecord | None: ...

    async def delete_workout_snapshots_for_entries(
        self, session_id: str, entry_ids: set[str]
    ) -> None: ...

    async def delete_workout_snapshots_for_session(self, session_id: str) -> None: ...

    async def recover_interrupted_workout_saves(self) -> int: ...

    async def replace_exercises(self, exercises: list[CatalogExercise]) -> None: ...

    async def count_exercises(self) -> int: ...
