-- 006_expand_exercise_catalog.sql
-- 动作目录扩容（§1–§4）：新增 aliases_json 列；既有 27 行只补 aliases；
-- 插入 83 条新增动作（60 可推荐 / 50 仅记录）。
-- 由 backend/tools/build_exercise_catalog.py 依据 backend/tools/exercise_catalog.json 与
-- exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd 生成：不要手工编辑，改目录 JSON 后重跑脚本。
-- 不含媒体 URL、instructions、target 与 muscle_group；既有行的 ID、行内容、
-- recommendable、source_ref 与 attribution 一律不动。

ALTER TABLE exercises
ADD COLUMN aliases_json TEXT NOT NULL DEFAULT '[]'
CHECK (json_valid(aliases_json));

-- 既有 27 行的常见别名（通用别名只落在唯一默认动作上）
UPDATE exercises SET aliases_json = '["深蹲", "杠铃深蹲", "barbell full squat"]' WHERE id = 'barbell-back-squat';
UPDATE exercises SET aliases_json = '["卧推", "杠铃卧推", "barbell bench press"]' WHERE id = 'barbell-bench-press';
UPDATE exercises SET aliases_json = '["杠铃划船", "俯身杠铃划船", "barbell bent over row"]' WHERE id = 'barbell-bent-over-row';
UPDATE exercises SET aliases_json = '["硬拉", "杠铃硬拉", "barbell deadlift"]' WHERE id = 'barbell-deadlift';
UPDATE exercises SET aliases_json = '["罗马尼亚硬拉", "杠铃RDL", "barbell romanian deadlift"]' WHERE id = 'barbell-romanian-deadlift';
UPDATE exercises SET aliases_json = '["分腿蹲", "哑铃分腿蹲", "dumbbell single leg split squat"]' WHERE id = 'bulgarian-split-squat';
UPDATE exercises SET aliases_json = '["过顶臂屈伸", "绳索臂屈伸", "cable overhead triceps extension (rope attachment)"]' WHERE id = 'cable-overhead-triceps-extension';
UPDATE exercises SET aliases_json = '["三头下压", "绳索三头下压", "cable pushdown"]' WHERE id = 'cable-pushdown';
UPDATE exercises SET aliases_json = '["哑铃卧推", "dumbbell bench press"]' WHERE id = 'dumbbell-bench-press';
UPDATE exercises SET aliases_json = '["二头弯举", "哑铃二头弯举", "dumbbell biceps curl"]' WHERE id = 'dumbbell-biceps-curl';
UPDATE exercises SET aliases_json = '["上斜哑铃卧推", "哑铃上斜推胸", "dumbbell incline bench press"]' WHERE id = 'dumbbell-incline-bench-press';
UPDATE exercises SET aliases_json = '["侧平举", "哑铃侧举", "dumbbell lateral raise"]' WHERE id = 'dumbbell-lateral-raise';
UPDATE exercises SET aliases_json = '["反向飞鸟", "哑铃后束飞鸟", "dumbbell reverse fly"]' WHERE id = 'dumbbell-reverse-fly';
UPDATE exercises SET aliases_json = '["前水平支撑", "front lever"]' WHERE id = 'front-lever';
UPDATE exercises SET aliases_json = '["悬挂举腿", "单杠举腿", "hanging leg raise"]' WHERE id = 'hanging-leg-raise';
UPDATE exercises SET aliases_json = '["下拉", "绳索下拉", "cable pulldown"]' WHERE id = 'lat-pulldown';
UPDATE exercises SET aliases_json = '["器械腿屈伸", "坐姿腿屈伸", "lever leg extension"]' WHERE id = 'leg-extension';
UPDATE exercises SET aliases_json = '["腿举", "器械腿举", "sled 45° leg press"]' WHERE id = 'leg-press-45';
UPDATE exercises SET aliases_json = '["站姿提踵", "器械提踵", "lever standing calf raise"]' WHERE id = 'machine-standing-calf-raise';
UPDATE exercises SET aliases_json = '["单臂划船", "哑铃单臂划船", "dumbbell one arm bent-over row"]' WHERE id = 'one-arm-dumbbell-row';
UPDATE exercises SET aliases_json = '["双杠臂屈伸", "自重臂屈伸", "chest dip"]' WHERE id = 'parallel-bar-dip';
UPDATE exercises SET aliases_json = '["平板", "plank"]' WHERE id = 'plank';
UPDATE exercises SET aliases_json = '["引体向上", "引体", "pull-up"]' WHERE id = 'pull-up';
UPDATE exercises SET aliases_json = '["划船", "绳索划船", "cable seated row"]' WHERE id = 'seated-cable-row';
UPDATE exercises SET aliases_json = '["哑铃肩推", "坐姿哑铃推举", "dumbbell seated shoulder press"]' WHERE id = 'seated-dumbbell-shoulder-press';
UPDATE exercises SET aliases_json = '["腿弯举", "器械坐姿腿弯举", "lever seated leg curl"]' WHERE id = 'seated-leg-curl';
UPDATE exercises SET aliases_json = '["负重引体向上", "加重引体", "weighted pull-up"]' WHERE id = 'weighted-pull-up';

-- 83 条新增动作：source_ref 固定 exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:<source_id>，attribution 使用纯数据来源声明
INSERT INTO exercises (
    id, standard_name_zh, equipment_variant, record_type, load_convention,
    min_load_increment_kg, recommendable, modes_json, aliases_json, source_ref, attribution
) VALUES
    ('barbell-bench-squat', '杠铃箱式深蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["箱式深蹲", "杠铃凳上深蹲", "barbell bench squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0026', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-clean-and-press', '杠铃高翻推举', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["髋铰链", "垂直推"]', '["高翻推举", "杠铃高翻上举", "barbell clean and press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0028', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-close-grip-bench-press', '杠铃窄距卧推', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["水平推", "肘伸"]', '["窄距卧推", "窄握卧推", "barbell close-grip bench press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0030', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-curl', '杠铃弯举', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["肘屈"]', '["杠铃二头弯举", "站姿杠铃弯举", "barbell curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0031', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-decline-bench-press', '杠铃下斜卧推', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["水平推"]', '["下斜卧推", "杠铃下斜推胸", "barbell decline bench press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0033', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-front-squat', '杠铃前蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["深蹲"]', '["前蹲", "杠铃颈前深蹲", "barbell front squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0042', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-good-morning', '杠铃早安式', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["髋铰链"]', '["杠铃早安式体前屈", "杠铃体前屈", "barbell good morning"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0044', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-hack-squat', '杠铃哈克深蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["哈克深蹲", "杠铃哈克机深蹲", "barbell hack squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0046', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-incline-bench-press', '杠铃上斜卧推', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["水平推", "垂直推"]', '["上斜卧推", "杠铃上斜推胸", "barbell incline bench press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0047', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-jump-squat', '杠铃跳跃深蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["跳跃深蹲", "杠铃跳跃蹲", "barbell jump squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0053', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-lunge', '杠铃箭步蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["深蹲"]', '["杠铃弓步蹲", "负重箭步蹲", "barbell lunge"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0054', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-lying-preacher-curl', '杠铃俯卧牧师凳弯举', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["肘屈"]', '["杠铃俯卧弯举", "杠铃俯卧斜托弯举", "barbell lying preacher curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0059', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-overhead-squat', '杠铃过顶深蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["过顶深蹲", "杠铃抓举深蹲", "barbell overhead squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0069', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-preacher-curl', '杠铃牧师凳弯举', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["肘屈"]', '["杠铃牧师椅弯举", "杠铃斜托弯举", "barbell preacher curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0070', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-rack-pull', '杠铃架上拉', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["髋铰链"]', '["架上拉", "杠铃架拉", "barbell rack pull"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0074', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-rear-delt-row', '杠铃后束划船', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["水平拉"]', '["杠铃后三角划船", "杠铃后肩划船", "barbell rear delt row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0076', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-seated-overhead-press', '杠铃坐姿肩推', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["垂直推"]', '["杠铃肩推", "坐姿杠铃推举", "barbell seated overhead press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0091', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-shrug', '杠铃耸肩', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["肩孤立"]', '["杠铃斜方耸肩", "负重耸肩", "barbell shrug"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0095', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-single-leg-split-squat', '杠铃单腿分腿蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["杠铃单腿蹲", "杠铃分腿蹲", "barbell single leg split squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0099', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-step-up', '杠铃登台阶', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["杠铃上台阶", "负重登台阶", "barbell step-up"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0114', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-straight-leg-deadlift', '杠铃直腿硬拉', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["髋铰链"]', '["直腿硬拉", "杠铃直腿拉", "barbell straight leg deadlift"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0116', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-sumo-deadlift', '杠铃相扑硬拉', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["髋铰链"]', '["相扑硬拉", "宽站距硬拉", "barbell sumo deadlift"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0117', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-upright-row', '杠铃直立划船', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 1, '["肩孤立"]', '["直立划船", "杠铃上提", "barbell upright row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0120', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('barbell-zercher-squat', '杠铃泽奇深蹲', 'barbell', 'reps_weight', 'barbell_includes_bar_total', 2.5, 0, '["深蹲"]', '["泽奇深蹲", "杠铃抱胸深蹲", "barbell zercher squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0127', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('bench-dip-on-floor', '自重地面臂屈伸', 'bodyweight', 'reps_bodyweight', NULL, NULL, 0, '["肘伸"]', '["地面臂屈伸", "自重三头臂屈伸", "bench dip on floor"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1399', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-curl', '绳索弯举', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["肘屈"]', '["绳索二头弯举", "拉力器弯举", "cable curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0868', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-front-raise', '绳索前平举', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["肩孤立"]', '["拉力器前平举", "绳索单臂前平举", "cable front raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0162', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-incline-fly', '绳索上斜飞鸟', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["水平推"]', '["绳索斜凳飞鸟", "拉力器上斜飞鸟", "cable incline fly"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0171', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-kickback', '绳索臂后伸', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["肘伸"]', '["拉力器臂后伸", "绳索三头后伸", "cable kickback"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0860', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-kneeling-crunch', '绳索跪姿卷腹', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["核心"]', '["绳索跪姿收腹", "拉力器跪姿卷腹", "cable kneeling crunch"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0175', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-lateral-raise', '绳索侧平举', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["肩孤立"]', '["拉力器侧平举", "绳索单臂侧平举", "cable lateral raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0178', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-overhead-curl', '绳索过顶弯举', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["肘屈"]', '["绳索过顶二头弯举", "拉力器头顶弯举", "cable overhead curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1636', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-preacher-curl', '绳索牧师凳弯举', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["肘屈"]', '["绳索牧师椅弯举", "拉力器斜托弯举", "cable preacher curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0195', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-seated-crunch', '绳索坐姿卷腹', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["核心"]', '["绳索卷腹", "拉力器坐姿卷腹", "cable seated crunch"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0212', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-seated-rear-lateral-raise', '绳索坐姿反式飞鸟', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["肩孤立"]', '["绳索坐姿后束飞鸟", "拉力器反式飞鸟", "cable seated rear lateral raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0215', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-seated-wide-grip-row', '绳索坐姿宽距划船', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["水平拉"]', '["绳索宽握划船", "拉力器宽距划船", "cable seated wide-grip row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0218', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-shoulder-press', '绳索站姿肩推', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["垂直推"]', '["绳索肩推", "拉力器肩推", "cable shoulder press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0219', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-shrug', '绳索耸肩', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["肩孤立"]', '["拉力器耸肩", "绳索斜方耸肩", "cable shrug"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0220', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-standing-calf-raise', '绳索站姿提踵', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["小腿（踝跖屈）"]', '["绳索提踵", "拉力器站姿提踵", "cable standing calf raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1375', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-straight-arm-pulldown', '绳索直臂下拉', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["垂直拉"]', '["直臂下拉", "绳索直臂下压", "cable straight arm pulldown"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0238', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-underhand-pulldown', '绳索反握下拉', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["垂直拉"]', '["绳索反握高位下拉", "拉力器反握下拉", "cable underhand pulldown"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0245', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('cable-upright-row', '绳索直立划船', 'cable', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["肩孤立"]', '["拉力器直立划船", "绳索上提", "cable upright row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0246', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('chin-up', '自重反手引体向上', 'bodyweight', 'reps_bodyweight', NULL, NULL, 1, '["垂直拉"]', '["反手引体", "反手引体向上", "chin-up"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1326', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-arnold-press', '哑铃阿诺德推举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["垂直推"]', '["阿诺德推举", "阿诺德肩推", "dumbbell arnold press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:2137', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-concentration-curl', '哑铃集中弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘屈"]', '["集中弯举", "哑铃单臂集中弯举", "dumbbell concentration curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0297', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-deadlift', '哑铃硬拉', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["髋铰链"]', '["哑铃传统硬拉", "哑铃屈髋拉", "dumbbell deadlift"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0300', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-fly', '哑铃飞鸟', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["水平推"]', '["哑铃平板飞鸟", "哑铃扩胸", "dumbbell fly"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0308', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-front-raise', '哑铃前平举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["肩孤立"]', '["前平举", "哑铃前举", "dumbbell front raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0310', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-goblet-squat', '哑铃高脚杯深蹲', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["深蹲"]', '["高脚杯深蹲", "杯式深蹲", "dumbbell goblet squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1760', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-hammer-curl', '哑铃锤式弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["肘屈"]', '["锤式弯举", "哑铃垂式弯举", "dumbbell hammer curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0313', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-incline-curl', '哑铃上斜弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘屈"]', '["上斜哑铃弯举", "哑铃斜凳弯举", "dumbbell incline curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0318', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-incline-fly', '哑铃上斜飞鸟', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["水平推"]', '["上斜飞鸟", "哑铃上斜扩胸", "dumbbell incline fly"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0319', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-kickback', '哑铃臂后伸', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘伸"]', '["哑铃三头后伸", "哑铃后撑", "dumbbell kickback"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0333', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-lunge', '哑铃箭步蹲', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["深蹲"]', '["哑铃弓步蹲", "哑铃行走箭步", "dumbbell lunge"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0336', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-lying-triceps-extension', '哑铃仰卧臂屈伸', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘伸"]', '["哑铃仰卧三头屈伸", "哑铃碎颅者", "dumbbell lying triceps extension"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0351', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-preacher-curl', '哑铃牧师凳弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘屈"]', '["哑铃牧师椅弯举", "哑铃斜托弯举", "dumbbell preacher curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0372', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-preacher-hammer-curl', '哑铃牧师凳锤式弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘屈"]', '["哑铃牧师椅锤式弯举", "哑铃斜托锤式弯举", "dumbbell preacher hammer curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0370', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-reverse-grip-biceps-curl', '哑铃反握弯举', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["肘屈"]', '["哑铃反握二头弯举", "哑铃正握弯举", "dumbbell reverse grip biceps curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0382', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-romanian-deadlift', '哑铃罗马尼亚硬拉', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["髋铰链"]', '["哑铃RDL", "哑铃直腿硬拉", "dumbbell romanian deadlift"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1459', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-seated-calf-raise', '哑铃坐姿提踵', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["小腿（踝跖屈）"]', '["哑铃小腿提踵", "坐姿哑铃负重提踵", "dumbbell seated calf raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1379', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-shrug', '哑铃耸肩', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["肩孤立"]', '["哑铃斜方耸肩", "哑铃负重耸肩", "dumbbell shrug"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0406', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-side-bend', '哑铃体侧屈', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["核心"]', '["哑铃侧屈", "负重侧屈", "dumbbell side bend"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0407', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-single-leg-deadlift', '哑铃单腿硬拉', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 1, '["髋铰链"]', '["单腿硬拉", "哑铃单腿罗马尼亚硬拉", "dumbbell single leg deadlift"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1757', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-squat', '哑铃深蹲', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["深蹲"]', '["哑铃负重深蹲", "双手哑铃深蹲", "dumbbell squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0413', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-standing-overhead-press', '哑铃站姿肩推', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["垂直推"]', '["哑铃站姿推举", "哑铃站姿上推", "dumbbell standing overhead press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0426', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('dumbbell-step-up', '哑铃登台阶', 'dumbbell', 'reps_weight', 'dumbbell_per_hand', 2.5, 0, '["深蹲"]', '["哑铃上台阶", "哑铃负重登台阶", "dumbbell step-up"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0431', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('front-plank-with-twist', '自重转体平板支撑', 'bodyweight', 'time', NULL, NULL, 0, '["核心"]', '["转体平板支撑", "平板支撑转体", "front plank with twist"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0464', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('hanging-straight-leg-raise', '自重悬垂直腿举', 'bodyweight', 'reps_bodyweight', NULL, NULL, 0, '["核心"]', '["悬垂直腿举", "单杠直腿举", "hanging straight leg raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0475', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('hyperextension', '自重背部伸展', 'bodyweight', 'reps_bodyweight', NULL, NULL, 0, '["髋铰链"]', '["背部伸展", "山羊挺身", "hyperextension"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0489', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('inverted-row', '自重反向划船', 'bodyweight', 'reps_bodyweight', NULL, NULL, 1, '["水平拉"]', '["反向划船", "自重仰卧划船", "inverted row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0499', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-chest-press', '器械坐姿推胸', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["水平推"]', '["器械推胸", "坐姿推胸器", "lever chest press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0577', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-front-pulldown', '器械前置下拉', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["垂直拉"]', '["器械下拉", "前置下拉器", "lever front pulldown"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0579', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-lying-leg-curl', '器械俯卧腿弯举', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["膝屈"]', '["俯卧腿弯举", "器械俯身腿弯举", "lever lying leg curl"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0586', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-seated-calf-raise', '器械坐姿提踵', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["小腿（踝跖屈）"]', '["坐姿提踵", "器械小腿提踵", "lever seated calf raise"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0594', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-seated-row', '器械坐姿划船', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 1, '["水平拉"]', '["器械划船", "坐姿划船器", "lever seated row"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1350', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('lever-shoulder-press', '器械坐姿肩推', 'leverage_machine', 'reps_weight', 'machine_pin_displayed_value', 5.0, 0, '["垂直推"]', '["器械肩推", "坐姿推肩器", "lever shoulder press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0603', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('mountain-climber', '自重登山跑', 'bodyweight', 'reps_bodyweight', NULL, NULL, 1, '["核心"]', '["登山跑", "俯撑提膝", "mountain climber"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0630', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('push-up', '自重俯卧撑', 'bodyweight', 'reps_bodyweight', NULL, NULL, 1, '["水平推"]', '["俯卧撑", "伏地挺身", "push-up"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0662', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('reverse-crunch', '自重反向卷腹', 'bodyweight', 'reps_bodyweight', NULL, NULL, 0, '["核心"]', '["反向卷腹", "仰卧反向缩腹", "reverse crunch"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0872', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('sled-45-calf-press', '器械45°提踵', 'sled_machine', 'reps_weight', 'plate_loaded_total_excluding_empty', 2.5, 0, '["小腿（踝跖屈）"]', '["器械45度提踵", "雪橇机提踵", "sled 45° calf press"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0738', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('sled-hack-squat', '器械哈克深蹲', 'sled_machine', 'reps_weight', 'plate_loaded_total_excluding_empty', 2.5, 0, '["深蹲"]', '["器械哈克机深蹲", "雪橇机哈克深蹲", "sled hack squat"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:0743', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('weighted-straight-bar-dip', '负重直杠臂屈伸', 'weighted', 'reps_weight', 'external_added_weight', 5.0, 1, '["垂直推", "肘伸"]', '["负重直杠双杠臂屈伸", "加重直杠臂屈伸", "weighted straight bar dip"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:3313', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)'),
    ('wide-hand-push-up', '自重宽距俯卧撑', 'bodyweight', 'reps_bodyweight', NULL, NULL, 0, '["水平推"]', '["宽距俯卧撑", "宽手俯卧撑", "wide hand push up"]', 'exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd:1311', 'exercises-dataset (MIT, © 2026 Hasan Emir Yıldırım)');
